[package]
name = "ecies-ed25519"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.6.4"
curve25519-dalek = { version = "4.1.3", features = ["legacy_compatibility"] }
thiserror = "2.0.12"
hex = "0.4.3"
zeroize = "1.8.1"
aes-gcm = { version = "0.10.3" }
sha2 = { version = "0.10.8" }
digest = { version = "0.10.7" }
hkdf = { version = "0.12.4" }